print("Hello! My name is Alan AI!")
print("(please click enter at every space)")
input()
print("Today we can have a conversation!")
input()
name=input("What is your name? ")
input()
print(f"Hello {name}!") 
input()
feeling=input("How has your day been? ")
input()
print(f"Wow! My day has been {feeling} too.")
action=input("What are you going to do today? ")
input()
print(f"{action} sounds really fun.")
input("What did you have for breakfast?")
print("MMMM YUM! That sounds delicious.")
print()
print("For breakfast, I had a burrito.")
print()
print("Well it looks like I have to go.")
print()
print("But I was really nice to meet you!")
print()
print("Maybe we could talk some other time...")
print()
print("Goodbye!")